services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .postgres.env
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gw

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - redis-data:/data
    networks:
      - gw

  backend:
    image: vpbuyanov/gw-backend-go:latest
    container_name: backend
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - server-data:/var/lib/server/data
      - './config.yaml:/config.yaml'
    depends_on:
      - postgres
    networks:
      - gw

  minio:
    image: minio/minio
    container_name: minio
    expose:
      - 9000
    environment:
      MINIO_ROOT_USER: localadmin
      MINIO_ROOT_PASSWORD: localpassword
    volumes:
      - minio-data:/data
    command: server /data
    restart: unless-stopped
    networks:
      - gw

  frontend:
    image: vpbuyanov/gw-frontend:latest
    container_name: frontend
    restart: unless-stopped
    volumes:
      - './cert/fullchain.pem:/cert/fullchain.pem'
      - './cert/privkey.pem:/cert/privkey.pem'
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gw

volumes:
  redis-data:
  server-data:
  postgres-data:
  minio-data:

networks:
  gw: